### ISSUE TITLE
no work for me 

### ISSUE THREAD

**Issue by nowind** [NaniteFactory/dllmain#1]
git clone and make ,but not work . go version 1.12.5

**Comment by NaniteFactory** [comment]
![1](https://user-images.githubusercontent.com/10949969/58362706-09db1f80-7ed5-11e9-81f2-dc8cdbe6c47d.PNG)

Works for me. I've tested it on Windows 10. Could you describe your issue in more detail?

**Comment by nowind** [comment]
when i run go build -i -v -o ${OUT}.dll -buildmode=c-shared -ldflags "-w -s -X main.version=123"   it work..but go build -i -v -o ${OUT}.dll -buildmode=c-shared -ldflags "-w -s -X main.version=1.2" main.go dllmain.go it not work. my fault

**Comment by NaniteFactory** [comment]
ok, glad your build was successful xD

**Comment by Hello-xBugs** [comment]
are you can use Loadbrary("my.dll") in c++ ?
